### ISSUE TITLE
No JSON Response Body when Login with 2FA

### ISSUE THREAD

**Issue by anubhavranjan** [FusionAuth/fusionauth-netcore-client#3] opened 2019-10-21 16:53 UTC
### Description 
I have enabled 2FA for one of the test users.
Now when I try to perform the login using the FusionAuthClient.Login(LoginRequest) method, all I see is the response with code 242 but no twoFactorId

### Expected behavior
After performing the Login, I should get the twoFactorId for performing the 2FA

### Screenshots
![image](https://user-images.githubusercontent.com/6568809/67224921-e39fb880-f44f-11e9-9e36-f83c3ed159a0.png)

### Platform
 - Server: IIS Express, .Net Core
 - OS: Windows 10
 - Browser + version: Microsoft Edge (Insider)

### Additional context
As seen in the screenshot, the statusCode is 242 but there are no additional data provided.

**Comment by robotdan** [comment] 2019-10-21 17:08
Strange, currently unable to reproduce. Perhaps there is an issue with the Netcore client itself.

**Comment by tyduptyler13** [comment] 2019-11-20 04:13
This is likely fixed with the #4 fix.

**Comment by robotdan** [comment] 2019-11-20 14:36
Closing as fixed under #4 . Thanks @anubhavranjan for reporting!

**Closed by robotdan** 2019-11-20 14:36 UTC
Labels: bug
